### ISSUE TITLE
Refactoring needed $$$

### ISSUE THREAD

**Issue by mtravnicek** [amihaiemil/elasticlunr-search-widget#22]
@amihaiemil I will pay you 15 $ ^_^ if you properly refactor this class
https://github.com/amihaiemil/elasticlunr-search-widget/blob/master/src/js/components/Input.js
hint: magic numbers, duplicit code...

**Comment by amihaiemil** [comment]
@mtravnicek You are right, that class does have some issues indeed. However, if you want to make it better, please open separate Github Issues for each problem, clearly state what the problem is and maybe suggest a solution. 

We are not in the same office to ask each other: "hey, what did you mean by **hints**?"

The most important thing in [XDSD](https://www.xdsd.org/) is traceability of changes. Each change should be associated with a proper Issue (the Task) and a proper PR, linking to the Issue and being focused only on solving one problem (i.e. 1 PR per topic, don't solve more things in a single PR).
